server:
  port: 8010
spring:
  application:
    name: provider
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.46.212.0:26000/labms?currentSchema=public
    username: lab_admin
    password: "Abcd@123"

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
shiro-redis:
  enable: true
  redis-manager:
    host: 127.0.0.1:6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization